[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
glam = "0.27"
tracing = "0.1"
tobj = "4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-time = "1"
